[versions]
maven-group = "band.kessokuteatime"
archives-name = "taptab"
mod = "3.3.0"
loader = "fabric"

minecraft = "1.20"
yarn = "1.20+build.1"
fabric-loader = "0.15.7"
fabric-api = "0.83.0+1.20"
fabric-loom = "1.6-SNAPSHOT"
modpublisher = "2.1.0"

# id
id-modrinth = "id"
id-curseforge = "id"

# display
display-name = "Tap Tab"
display-loader = "Fabric"
display-version = "1.20.x"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
modpublisher = { id = "com.hypherionmc.modutils.modpublisher", version.ref = "modpublisher" }

[bundles]
fabric = ["fabric-loader", "fabric-api"]
